package com.hhdys.dao;

import com.hhdys.model.AccountFuncAss;
import com.hhdys.model.AccountFuncAssExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountFuncAssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int countByExample(AccountFuncAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int deleteByExample(AccountFuncAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int insert(AccountFuncAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int insertSelective(AccountFuncAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    List<AccountFuncAss> selectByExample(AccountFuncAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    AccountFuncAss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int updateByExampleSelective(@Param("record") AccountFuncAss record, @Param("example") AccountFuncAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int updateByExample(@Param("record") AccountFuncAss record, @Param("example") AccountFuncAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int updateByPrimaryKeySelective(AccountFuncAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_func_ass
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    int updateByPrimaryKey(AccountFuncAss record);
}