package com.hhdys.dao;

import com.hhdys.model.DepartRoleAss;
import com.hhdys.model.DepartRoleAssExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartRoleAssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int countByExample(DepartRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int deleteByExample(DepartRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int insert(DepartRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int insertSelective(DepartRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    List<DepartRoleAss> selectByExample(DepartRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    DepartRoleAss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int updateByExampleSelective(@Param("record") DepartRoleAss record, @Param("example") DepartRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int updateByExample(@Param("record") DepartRoleAss record, @Param("example") DepartRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int updateByPrimaryKeySelective(DepartRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_role_ass
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    int updateByPrimaryKey(DepartRoleAss record);
}