package com.hhdys.dao;

import com.hhdys.model.PageFunc;
import com.hhdys.model.PageFuncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PageFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int countByExample(PageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int deleteByExample(PageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int insert(PageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int insertSelective(PageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    List<PageFunc> selectByExample(PageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    PageFunc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int updateByExampleSelective(@Param("record") PageFunc record, @Param("example") PageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int updateByExample(@Param("record") PageFunc record, @Param("example") PageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int updateByPrimaryKeySelective(PageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    int updateByPrimaryKey(PageFunc record);
}