package com.hhdys.dao;

import com.hhdys.model.PositionRoleAss;
import com.hhdys.model.PositionRoleAssExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PositionRoleAssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int countByExample(PositionRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int deleteByExample(PositionRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int insert(PositionRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int insertSelective(PositionRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    List<PositionRoleAss> selectByExample(PositionRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    PositionRoleAss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int updateByExampleSelective(@Param("record") PositionRoleAss record, @Param("example") PositionRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int updateByExample(@Param("record") PositionRoleAss record, @Param("example") PositionRoleAssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int updateByPrimaryKeySelective(PositionRoleAss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_role_ass
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    int updateByPrimaryKey(PositionRoleAss record);
}