package com.hhdys.model;

public class AccountFuncAss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_func_ass.id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_func_ass.account_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    private int accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_func_ass.func_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    private int funcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_func_ass.id
     *
     * @return the value of account_func_ass.id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_func_ass.id
     *
     * @param id the value for account_func_ass.id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_func_ass.account_id
     *
     * @return the value of account_func_ass.account_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public int getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_func_ass.account_id
     *
     * @param accountId the value for account_func_ass.account_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_func_ass.func_id
     *
     * @return the value of account_func_ass.func_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public int getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_func_ass.func_id
     *
     * @param funcId the value for account_func_ass.func_id
     *
     * @mbggenerated Wed Oct 09 11:03:51 CST 2013
     */
    public void setFuncId(int funcId) {
        this.funcId = funcId;
    }
}