package com.hhdys.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.department
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.age
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.inuse
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int inuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private long lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.position
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    private int position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.department
     *
     * @return the value of account.department
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.department
     *
     * @param department the value for account.department
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setDepartment(int department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setSex(int sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.age
     *
     * @return the value of account.age
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.age
     *
     * @param age the value for account.age
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setAge(int age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.inuse
     *
     * @return the value of account.inuse
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getInuse() {
        return inuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.inuse
     *
     * @param inuse the value for account.inuse
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setInuse(int inuse) {
        this.inuse = inuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login_time
     *
     * @return the value of account.last_login_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public long getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login_time
     *
     * @param lastLoginTime the value for account.last_login_time
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setLastLoginTime(long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role
     *
     * @return the value of account.role
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role
     *
     * @param role the value for account.role
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setRole(int role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.position
     *
     * @return the value of account.position
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public int getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.position
     *
     * @param position the value for account.position
     *
     * @mbggenerated Thu Apr 18 17:24:48 CST 2013
     */
    public void setPosition(int position) {
        this.position = position;
    }
}