package com.hhdys.model;

public class DepartRoleAss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart_role_ass.id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart_role_ass.department_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    private int departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart_role_ass.role_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    private int roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart_role_ass.id
     *
     * @return the value of depart_role_ass.id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart_role_ass.id
     *
     * @param id the value for depart_role_ass.id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart_role_ass.department_id
     *
     * @return the value of depart_role_ass.department_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public int getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart_role_ass.department_id
     *
     * @param departmentId the value for depart_role_ass.department_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart_role_ass.role_id
     *
     * @return the value of depart_role_ass.role_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public int getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart_role_ass.role_id
     *
     * @param roleId the value for depart_role_ass.role_id
     *
     * @mbggenerated Wed Aug 07 17:25:07 CST 2013
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
}