package com.hhdys.model;

public class PageFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_func.id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_func.page_id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    private int pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_func.func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    private String func;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_func.id
     *
     * @return the value of page_func.id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_func.id
     *
     * @param id the value for page_func.id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_func.page_id
     *
     * @return the value of page_func.page_id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public int getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_func.page_id
     *
     * @param pageId the value for page_func.page_id
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public void setPageId(int pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_func.func
     *
     * @return the value of page_func.func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public String getFunc() {
        return func;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_func.func
     *
     * @param func the value for page_func.func
     *
     * @mbggenerated Wed Aug 07 15:17:58 CST 2013
     */
    public void setFunc(String func) {
        this.func = func == null ? null : func.trim();
    }
}