package com.hhdys.model;

public class PositionRoleAss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_role_ass.id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_role_ass.position_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    private int positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_role_ass.role_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    private int roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_role_ass.id
     *
     * @return the value of position_role_ass.id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_role_ass.id
     *
     * @param id the value for position_role_ass.id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_role_ass.position_id
     *
     * @return the value of position_role_ass.position_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public int getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_role_ass.position_id
     *
     * @param positionId the value for position_role_ass.position_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public void setPositionId(int positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_role_ass.role_id
     *
     * @return the value of position_role_ass.role_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public int getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_role_ass.role_id
     *
     * @param roleId the value for position_role_ass.role_id
     *
     * @mbggenerated Mon Aug 19 10:12:59 CST 2013
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
}