package com.hhdys.model;

public class RoleFuncAss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_func_ass.id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_func_ass.role_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    private int roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_func_ass.func_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    private int funcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_func_ass.id
     *
     * @return the value of role_func_ass.id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_func_ass.id
     *
     * @param id the value for role_func_ass.id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_func_ass.role_id
     *
     * @return the value of role_func_ass.role_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public int getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_func_ass.role_id
     *
     * @param roleId the value for role_func_ass.role_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_func_ass.func_id
     *
     * @return the value of role_func_ass.func_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public int getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_func_ass.func_id
     *
     * @param funcId the value for role_func_ass.func_id
     *
     * @mbggenerated Mon Aug 19 14:24:20 CST 2013
     */
    public void setFuncId(int funcId) {
        this.funcId = funcId;
    }
}